# -*- coding: utf-8 -*-
"""Actividad5.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16GGEgK4QAnNi54U-9wVc7dNRmecr-6Qh
"""

a=int(input("ingrese numero:"))
print(a**2, a**3)

if a==4:
  j=int(input("numero adicional"))
  h=str(j)+"veces"
  print("verdadero")

h="hola mundo"
print(h)

a=int(input("Ingrese numero"))
b=int(input("ingrese numero"))

if a>b:
  print("A es mayor que B")
elif a==b:
  print("A es igual a B")
else:
  print("A es menor que B")

from types import EllipsisType
a=int(input("Ingrese nota 1: "))
b=int(input("ingrese nota 2: "))
c=int(input("Ingrese numero"))
d=int(input("ingrese numero"))
e=int(input("Ingrese numero"))



if a > 0 and a>5 and b > 0 and b>5 and c > 0 and c>5 and d> 0 and d>5 and e > 0 and e>5 :
  x= (a*0.30 + b*0.15 + c*0.15 + d*0.20 + e*0.20)/ 5
  if x >=3 :
    print("Aprobado")
else:
  print(" Copia bien los datos")
print(x)

y=int(input("ingrese numero"))
z=int(input("ingrese numero"))
if y>z:
  x==1
if y==z:
 x=2
if y<z:
  x==3